<?php

/**
 * @file
 * Contains asu_footer.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function asu_footer_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the asu_footer module.
    case 'help.page.asu_footer':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Global footer for ASU web standards') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_theme().
 */
function asu_footer_theme($existing, $type, $theme, $path) {
  $templates = $path . '/templates';
  return [
    'asu_footer_block' => [
      'template' => 'asu-footer-block',
      'variables' => [
          'module_path' => NULL,
      ],
    ],
  ];
}


/**
 * Implements hook_preprocess_*()
 * Pass the module path as a variable
 */
function asu_footer_preprocess_asu_footer_block(&$variables, $hook) {
  $module_handler = Drupal::service('module_handler');
  $path = $module_handler->getModule('asu_footer')->getPath();

  $variables['module_path'] = $path;
}
